### ISSUE TITLE
Should the set/config methods borrow self mutably?

### ISSUE THREAD

**Issue by auscompgeek** [auscompgeek/ctre-rs#4]

**Comment by auscompgeek** [comment]
I imagine it probably won't be a problem in practice, but I could see teams try to concurrently change the setpoint of a Talon SRX and wonder why it's not behaving as they intend.

There's also the factory default, "config all settings", and "get all configs" functions in Phoenix v5.7. We probably want to ensure none of those run concurrently either.

**Comment by Lytigas** [comment]
At least in the WPILib HAL, it seems lots of things are behind a mutex. For user sanity, taking mutable references makes sense. It also helps hint that the method is going to actually do something. However, this choice could force users into unnecessary interior mutability. I currently lean towards taking `&mut self`.

**Comment by auscompgeek** [comment]
Looking at this again, @Lytigas raises a good point. I think I'll start by changing all the config calls to take `&mut self`, since those realistically should only be called at startup - constantly changing the config during a match would be a really bad idea.

I think the motion profiling calls are behind a mutex, so keeping those as borrowing self immutably would be fine, I guess.

**Comment by auscompgeek** [comment]
I think this is pretty much done now.
